let
    Source = Csv.Document(File.Contents("C:\Users\chest\Projects\Data_Analytics\global-corporate-esg-and-financial-analysis\esg_raw.csv"),[Delimiter=";", Columns=85, Encoding=1252, QuoteStyle=QuoteStyle.None]),
    #"Use First Row as Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
    #"Change Type" = Table.TransformColumnTypes(#"Use First Row as Headers",{{"domain", type text}, {"name", type text}, {"ticker", type text}, {"involvement.Alcoholic Beverages", type text}, {"involvement.Adult Entertainment", type text}, {"involvement.Gambling", type text}, {"involvement.Tobacco Products", type text}, {"involvement.Animal Testing", type text}, {"involvement.Fur and Specialty Leather", type text}, {"involvement.Controversial Weapons", type text}, {"involvement.Small Arms", type text}, {"involvement.Catholic Values", type text}, {"involvement.GMO", type text}, {"involvement.Military Contracting", type text}, {"involvement.Pesticides", type text}, {"involvement.Thermal Coal", type text}, {"involvement.Palm Oil", type text}, {"employees", type text}, {"industry", type text}, {"sector", type text}, {"altman_score", type text}, {"piotroski_score", type text}, {"Controversies.Environment", type text}, {"Controversies.Social", type text}, {"Controversies.Customers", type text}, {"Controversies.Human Rights & Community", type text}, {"Controversies.Labor Rights & Supply Chain", type text}, {"Controversies.Governance", type text}, {"Decarbonization Target.Target Year", type text}, {"Decarbonization Target.Comprehensiveness", type text}, {"Decarbonization Target.Ambition p.a.", type text}, {"Decarbonization Target.Decarbonization Target", type text}, {"Decarbonization Target.Decarbonization Target on Temperature Rise", type text}, {"Temperature Goal", type text}, {"sdg.No Poverty", type text}, {"sdg.No Hunger", type text}, {"sdg.Good Health and Well-Being", type text}, {"sdg.Quality Education", type text}, {"sdg.Gender Equality", type text}, {"sdg.Clean Water and Sanitation", type text}, {"sdg.Affordable and Clean Energy", type text}, {"sdg.Decent Work and Economic Growth", type text}, {"sdg.Industry, Innovation and Infrastructure", type text}, {"sdg.Reduced Inequalities", type text}, {"sdg.Sustainable Cities and Communities", type text}, {"sdg.Responsible Consumption and Production", type text}, {"sdg.Climate Action", type text}, {"sdg.Life under Water", type text}, {"sdg.Life on Land", type text}, {"sdg.Peace, Justice and Strong Institutions", type text}, {"sdg.Partnerships for the Goals", type text}, {"esg", type text}, {"involvement_msci.Controversial Weapons", type text}, {"involvement_msci.Gambling", type text}, {"involvement_msci.Tobacco Products", type text}, {"involvement_msci.Alcoholic Beverages", type text}, {"Controversies.Supply Chain Labor Standards", type text}, {"Controversies", type text}, {"Decarbonization Target", type text}, {"sdg", type text}, {"Controversies.Collective Bargaining & Union", type text}, {"Controversies.Health & Safety", type text}, {"Controversies.Discrimination & Workforce Diversity", type text}, {"Controversies.Labor Management Relations", type text}, {"involvement", type text}, {"involvement_msci", type text}, {"Controversies.Anticompetitive Practices", type text}, {"Controversies.Privacy & Data Security", type text}, {"Controversies.Bribery & Fraud", type text}, {"Controversies.Governance Structures", type text}, {"Controversies.Customer Relations", type text}, {"Controversies.Product Safety & Quality", type text}, {"Controversies.Human Rights Concerns", type text}, {"Controversies.Energy & Climate Change", type text}, {"Controversies.Toxic Emissions & Waste", type text}, {"Controversies.Impact on Local Communities", type text}, {"Controversies.Biodiversity & Land Use", type text}, {"Controversies.Other", type text}, {"Controversies.Marketing & Advertising", type text}, {"Controversies.Civil Liberties", type text}, {"Controversies.Operational Waste (Non-Hazardous)", type text}, {"Controversies.Supply Chain Management", type text}, {"Controversies.Water Stress", type text}, {"Controversies.Child Labor", type text}, {"Controversies.Controversial Investments", type text}}),
    #"Replaced \n" = Table.ReplaceValue(#"Change Type","\n","",Replacer.ReplaceText,{"domain", "name", "ticker", "involvement.Alcoholic Beverages", "involvement.Adult Entertainment", "involvement.Gambling", "involvement.Tobacco Products", "involvement.Animal Testing", "involvement.Fur and Specialty Leather", "involvement.Controversial Weapons", "involvement.Small Arms", "involvement.Catholic Values", "involvement.GMO", "involvement.Military Contracting", "involvement.Pesticides", "involvement.Thermal Coal", "involvement.Palm Oil", "employees", "industry", "sector", "altman_score", "piotroski_score", "Controversies.Environment", "Controversies.Social", "Controversies.Customers", "Controversies.Human Rights & Community", "Controversies.Labor Rights & Supply Chain", "Controversies.Governance", "Decarbonization Target.Target Year", "Decarbonization Target.Comprehensiveness", "Decarbonization Target.Ambition p.a.", "Decarbonization Target.Decarbonization Target", "Decarbonization Target.Decarbonization Target on Temperature Rise", "Temperature Goal", "sdg.No Poverty", "sdg.No Hunger", "sdg.Good Health and Well-Being", "sdg.Quality Education", "sdg.Gender Equality", "sdg.Clean Water and Sanitation", "sdg.Affordable and Clean Energy", "sdg.Decent Work and Economic Growth", "sdg.Industry, Innovation and Infrastructure", "sdg.Reduced Inequalities", "sdg.Sustainable Cities and Communities", "sdg.Responsible Consumption and Production", "sdg.Climate Action", "sdg.Life under Water", "sdg.Life on Land", "sdg.Peace, Justice and Strong Institutions", "sdg.Partnerships for the Goals", "esg", "involvement_msci.Controversial Weapons", "involvement_msci.Gambling", "involvement_msci.Tobacco Products", "involvement_msci.Alcoholic Beverages", "Controversies.Supply Chain Labor Standards", "Controversies", "Decarbonization Target", "sdg", "Controversies.Collective Bargaining & Union", "Controversies.Health & Safety", "Controversies.Discrimination & Workforce Diversity", "Controversies.Labor Management Relations", "involvement", "involvement_msci", "Controversies.Anticompetitive Practices", "Controversies.Privacy & Data Security", "Controversies.Bribery & Fraud", "Controversies.Governance Structures", "Controversies.Customer Relations", "Controversies.Product Safety & Quality", "Controversies.Human Rights Concerns", "Controversies.Energy & Climate Change", "Controversies.Toxic Emissions & Waste", "Controversies.Impact on Local Communities", "Controversies.Biodiversity & Land Use", "Controversies.Other", "Controversies.Marketing & Advertising", "Controversies.Civil Liberties", "Controversies.Operational Waste (Non-Hazardous)", "Controversies.Supply Chain Management", "Controversies.Water Stress", "Controversies.Child Labor", "Controversies.Controversial Investments"}),
    #"Replaced %" = Table.ReplaceValue(#"Replaced \n","%","",Replacer.ReplaceText,{"domain", "name", "ticker", "involvement.Alcoholic Beverages", "involvement.Adult Entertainment", "involvement.Gambling", "involvement.Tobacco Products", "involvement.Animal Testing", "involvement.Fur and Specialty Leather", "involvement.Controversial Weapons", "involvement.Small Arms", "involvement.Catholic Values", "involvement.GMO", "involvement.Military Contracting", "involvement.Pesticides", "involvement.Thermal Coal", "involvement.Palm Oil", "employees", "industry", "sector", "altman_score", "piotroski_score", "Controversies.Environment", "Controversies.Social", "Controversies.Customers", "Controversies.Human Rights & Community", "Controversies.Labor Rights & Supply Chain", "Controversies.Governance", "Decarbonization Target.Target Year", "Decarbonization Target.Comprehensiveness", "Decarbonization Target.Ambition p.a.", "Decarbonization Target.Decarbonization Target", "Decarbonization Target.Decarbonization Target on Temperature Rise", "Temperature Goal", "sdg.No Poverty", "sdg.No Hunger", "sdg.Good Health and Well-Being", "sdg.Quality Education", "sdg.Gender Equality", "sdg.Clean Water and Sanitation", "sdg.Affordable and Clean Energy", "sdg.Decent Work and Economic Growth", "sdg.Industry, Innovation and Infrastructure", "sdg.Reduced Inequalities", "sdg.Sustainable Cities and Communities", "sdg.Responsible Consumption and Production", "sdg.Climate Action", "sdg.Life under Water", "sdg.Life on Land", "sdg.Peace, Justice and Strong Institutions", "sdg.Partnerships for the Goals", "esg", "involvement_msci.Controversial Weapons", "involvement_msci.Gambling", "involvement_msci.Tobacco Products", "involvement_msci.Alcoholic Beverages", "Controversies.Supply Chain Labor Standards", "Controversies", "Decarbonization Target", "sdg", "Controversies.Collective Bargaining & Union", "Controversies.Health & Safety", "Controversies.Discrimination & Workforce Diversity", "Controversies.Labor Management Relations", "involvement", "involvement_msci", "Controversies.Anticompetitive Practices", "Controversies.Privacy & Data Security", "Controversies.Bribery & Fraud", "Controversies.Governance Structures", "Controversies.Customer Relations", "Controversies.Product Safety & Quality", "Controversies.Human Rights Concerns", "Controversies.Energy & Climate Change", "Controversies.Toxic Emissions & Waste", "Controversies.Impact on Local Communities", "Controversies.Biodiversity & Land Use", "Controversies.Other", "Controversies.Marketing & Advertising", "Controversies.Civil Liberties", "Controversies.Operational Waste (Non-Hazardous)", "Controversies.Supply Chain Management", "Controversies.Water Stress", "Controversies.Child Labor", "Controversies.Controversial Investments"}),
    #"Replaced null" = Table.ReplaceValue(#"Replaced %","null","",Replacer.ReplaceValue,{"domain", "name", "ticker", "involvement.Alcoholic Beverages", "involvement.Adult Entertainment", "involvement.Gambling", "involvement.Tobacco Products", "involvement.Animal Testing", "involvement.Fur and Specialty Leather", "involvement.Controversial Weapons", "involvement.Small Arms", "involvement.Catholic Values", "involvement.GMO", "involvement.Military Contracting", "involvement.Pesticides", "involvement.Thermal Coal", "involvement.Palm Oil", "employees", "industry", "sector", "altman_score", "piotroski_score", "Controversies.Environment", "Controversies.Social", "Controversies.Customers", "Controversies.Human Rights & Community", "Controversies.Labor Rights & Supply Chain", "Controversies.Governance", "Decarbonization Target.Target Year", "Decarbonization Target.Comprehensiveness", "Decarbonization Target.Ambition p.a.", "Decarbonization Target.Decarbonization Target", "Decarbonization Target.Decarbonization Target on Temperature Rise", "Temperature Goal", "sdg.No Poverty", "sdg.No Hunger", "sdg.Good Health and Well-Being", "sdg.Quality Education", "sdg.Gender Equality", "sdg.Clean Water and Sanitation", "sdg.Affordable and Clean Energy", "sdg.Decent Work and Economic Growth", "sdg.Industry, Innovation and Infrastructure", "sdg.Reduced Inequalities", "sdg.Sustainable Cities and Communities", "sdg.Responsible Consumption and Production", "sdg.Climate Action", "sdg.Life under Water", "sdg.Life on Land", "sdg.Peace, Justice and Strong Institutions", "sdg.Partnerships for the Goals", "esg", "involvement_msci.Controversial Weapons", "involvement_msci.Gambling", "involvement_msci.Tobacco Products", "involvement_msci.Alcoholic Beverages", "Controversies.Supply Chain Labor Standards", "Controversies", "Decarbonization Target", "sdg", "Controversies.Collective Bargaining & Union", "Controversies.Health & Safety", "Controversies.Discrimination & Workforce Diversity", "Controversies.Labor Management Relations", "involvement", "involvement_msci", "Controversies.Anticompetitive Practices", "Controversies.Privacy & Data Security", "Controversies.Bribery & Fraud", "Controversies.Governance Structures", "Controversies.Customer Relations", "Controversies.Product Safety & Quality", "Controversies.Human Rights Concerns", "Controversies.Energy & Climate Change", "Controversies.Toxic Emissions & Waste", "Controversies.Impact on Local Communities", "Controversies.Biodiversity & Land Use", "Controversies.Other", "Controversies.Marketing & Advertising", "Controversies.Civil Liberties", "Controversies.Operational Waste (Non-Hazardous)", "Controversies.Supply Chain Management", "Controversies.Water Stress", "Controversies.Child Labor", "Controversies.Controversial Investments"}),
    #"Trimmed Text" = Table.TransformColumns(#"Replaced null",{{"domain", Text.Trim, type text}, {"name", Text.Trim, type text}, {"ticker", Text.Trim, type text}, {"involvement.Alcoholic Beverages", Text.Trim, type text}, {"involvement.Adult Entertainment", Text.Trim, type text}, {"involvement.Gambling", Text.Trim, type text}, {"involvement.Tobacco Products", Text.Trim, type text}, {"involvement.Animal Testing", Text.Trim, type text}, {"involvement.Fur and Specialty Leather", Text.Trim, type text}, {"involvement.Controversial Weapons", Text.Trim, type text}, {"involvement.Small Arms", Text.Trim, type text}, {"involvement.Catholic Values", Text.Trim, type text}, {"involvement.GMO", Text.Trim, type text}, {"involvement.Military Contracting", Text.Trim, type text}, {"involvement.Pesticides", Text.Trim, type text}, {"involvement.Thermal Coal", Text.Trim, type text}, {"involvement.Palm Oil", Text.Trim, type text}, {"employees", Text.Trim, type text}, {"industry", Text.Trim, type text}, {"sector", Text.Trim, type text}, {"altman_score", Text.Trim, type text}, {"piotroski_score", Text.Trim, type text}, {"Controversies.Environment", Text.Trim, type text}, {"Controversies.Social", Text.Trim, type text}, {"Controversies.Customers", Text.Trim, type text}, {"Controversies.Human Rights & Community", Text.Trim, type text}, {"Controversies.Labor Rights & Supply Chain", Text.Trim, type text}, {"Controversies.Governance", Text.Trim, type text}, {"Decarbonization Target.Target Year", Text.Trim, type text}, {"Decarbonization Target.Comprehensiveness", Text.Trim, type text}, {"Decarbonization Target.Ambition p.a.", Text.Trim, type text}, {"Decarbonization Target.Decarbonization Target", Text.Trim, type text}, {"Decarbonization Target.Decarbonization Target on Temperature Rise", Text.Trim, type text}, {"Temperature Goal", Text.Trim, type text}, {"sdg.No Poverty", Text.Trim, type text}, {"sdg.No Hunger", Text.Trim, type text}, {"sdg.Good Health and Well-Being", Text.Trim, type text}, {"sdg.Quality Education", Text.Trim, type text}, {"sdg.Gender Equality", Text.Trim, type text}, {"sdg.Clean Water and Sanitation", Text.Trim, type text}, {"sdg.Affordable and Clean Energy", Text.Trim, type text}, {"sdg.Decent Work and Economic Growth", Text.Trim, type text}, {"sdg.Industry, Innovation and Infrastructure", Text.Trim, type text}, {"sdg.Reduced Inequalities", Text.Trim, type text}, {"sdg.Sustainable Cities and Communities", Text.Trim, type text}, {"sdg.Responsible Consumption and Production", Text.Trim, type text}, {"sdg.Climate Action", Text.Trim, type text}, {"sdg.Life under Water", Text.Trim, type text}, {"sdg.Life on Land", Text.Trim, type text}, {"sdg.Peace, Justice and Strong Institutions", Text.Trim, type text}, {"sdg.Partnerships for the Goals", Text.Trim, type text}, {"esg", Text.Trim, type text}, {"involvement_msci.Controversial Weapons", Text.Trim, type text}, {"involvement_msci.Gambling", Text.Trim, type text}, {"involvement_msci.Tobacco Products", Text.Trim, type text}, {"involvement_msci.Alcoholic Beverages", Text.Trim, type text}, {"Controversies.Supply Chain Labor Standards", Text.Trim, type text}, {"Controversies", Text.Trim, type text}, {"Decarbonization Target", Text.Trim, type text}, {"sdg", Text.Trim, type text}, {"Controversies.Collective Bargaining & Union", Text.Trim, type text}, {"Controversies.Health & Safety", Text.Trim, type text}, {"Controversies.Discrimination & Workforce Diversity", Text.Trim, type text}, {"Controversies.Labor Management Relations", Text.Trim, type text}, {"involvement", Text.Trim, type text}, {"involvement_msci", Text.Trim, type text}, {"Controversies.Anticompetitive Practices", Text.Trim, type text}, {"Controversies.Privacy & Data Security", Text.Trim, type text}, {"Controversies.Bribery & Fraud", Text.Trim, type text}, {"Controversies.Governance Structures", Text.Trim, type text}, {"Controversies.Customer Relations", Text.Trim, type text}, {"Controversies.Product Safety & Quality", Text.Trim, type text}, {"Controversies.Human Rights Concerns", Text.Trim, type text}, {"Controversies.Energy & Climate Change", Text.Trim, type text}, {"Controversies.Toxic Emissions & Waste", Text.Trim, type text}, {"Controversies.Impact on Local Communities", Text.Trim, type text}, {"Controversies.Biodiversity & Land Use", Text.Trim, type text}, {"Controversies.Other", Text.Trim, type text}, {"Controversies.Marketing & Advertising", Text.Trim, type text}, {"Controversies.Civil Liberties", Text.Trim, type text}, {"Controversies.Operational Waste (Non-Hazardous)", Text.Trim, type text}, {"Controversies.Supply Chain Management", Text.Trim, type text}, {"Controversies.Water Stress", Text.Trim, type text}, {"Controversies.Child Labor", Text.Trim, type text}, {"Controversies.Controversial Investments", Text.Trim, type text}}),
    #"Removed Blank Rows" = Table.SelectRows(#"Trimmed Text", each not List.IsEmpty(List.RemoveMatchingItems(Record.FieldValues(_), {"", null}))),
    #"Removed Duplicates" = Table.Distinct(#"Removed Blank Rows"),
    #"Replaced t" = Table.ReplaceValue(#"Removed Duplicates","t","",Replacer.ReplaceText,{"Decarbonization Target.Comprehensiveness"}),
    #"Rename Columns" = Table.RenameColumns(
     #"Replaced t",
    {
        {"name", "company_name"},

        {"involvement.Alcoholic Beverages", "involvement_alcohol"},
        {"involvement.Adult Entertainment", "involvement_adult_entertainment"},
        {"involvement.Gambling", "involvement_gambling"},
        {"involvement.Tobacco Products", "involvement_tobacco"},
        {"involvement.Animal Testing", "involvement_animal_testing"},
        {"involvement.Fur and Specialty Leather", "involvement_fur_leather"},
        {"involvement.Controversial Weapons", "involvement_controversial_weapons"},
        {"involvement.Small Arms", "involvement_small_arms"},
        {"involvement.Catholic Values", "involvement_catholic_values"},
        {"involvement.GMO", "involvement_gmo"},
        {"involvement.Military Contracting", "involvement_military"},
        {"involvement.Pesticides", "involvement_pesticides"},
        {"involvement.Thermal Coal", "involvement_thermal_coal"},
        {"involvement.Palm Oil", "involvement_palm_oil"},

        {"Controversies.Environment", "controversy_environment"},
        {"Controversies.Social", "controversy_social"},
        {"Controversies.Customers", "controversy_customers"},
        {"Controversies.Human Rights & Community", "controversy_human_rights_community"},
        {"Controversies.Labor Rights & Supply Chain", "controversy_labor_supply_chain"},
        {"Controversies.Governance", "controversy_governance"},

        {"Decarbonization Target.Target Year", "decarb_target_year"},
        {"Decarbonization Target.Comprehensiveness", "decarb_target_comprehensiveness"},
        {"Decarbonization Target.Ambition p.a.", "decarb_target_ambition_pa"},
        {"Decarbonization Target.Decarbonization Target", "decarb_target"},
        {"Decarbonization Target.Decarbonization Target on Temperature Rise", "decarb_target_temp_rise"},

        {"Temperature Goal", "temperature_goal"},

        {"sdg.No Poverty", "sdg_no_poverty"},
        {"sdg.No Hunger", "sdg_no_hunger"},
        {"sdg.Good Health and Well-Being", "sdg_good_health"},
        {"sdg.Quality Education", "sdg_quality_education"},
        {"sdg.Gender Equality", "sdg_gender_equality"},
        {"sdg.Clean Water and Sanitation", "sdg_clean_water"},
        {"sdg.Affordable and Clean Energy", "sdg_clean_energy"},
        {"sdg.Decent Work and Economic Growth", "sdg_decent_work"},
        {"sdg.Industry, Innovation and Infrastructure", "sdg_industry_innovation"},
        {"sdg.Reduced Inequalities", "sdg_reduced_inequalities"},
        {"sdg.Sustainable Cities and Communities", "sdg_sustainable_cities"},
        {"sdg.Responsible Consumption and Production", "sdg_responsible_consumption"},
        {"sdg.Climate Action", "sdg_climate_action"},
        {"sdg.Life under Water", "sdg_life_below_water"},
        {"sdg.Life on Land", "sdg_life_on_land"},
        {"sdg.Peace, Justice and Strong Institutions", "sdg_peace_justice"},
        {"sdg.Partnerships for the Goals", "sdg_partnerships"},

        {"esg", "esg_score"},

        {"involvement_msci.Controversial Weapons", "msci_controversial_weapons"},
        {"involvement_msci.Gambling", "msci_gambling"},
        {"involvement_msci.Tobacco Products", "msci_tobacco"},
        {"involvement_msci.Alcoholic Beverages", "msci_alcohol"},

        {"Controversies.Supply Chain Labor Standards", "controversy_supply_chain_labor"},

        {"Controversies", "Controversies"},
        {"Decarbonization Target", "Decarbonization Target"},
        {"sdg", "Sdg"},

        {"Controversies.Collective Bargaining & Union", "controversy_collective_bargaining"},
        {"Controversies.Health & Safety", "controversy_health_safety"},
        {"Controversies.Discrimination & Workforce Diversity", "controversy_discrimination_diversity"},
        {"Controversies.Labor Management Relations", "controversy_labor_management"},

        {"involvement", "Involvement"},
        {"involvement_msci", "Involvement_Msci"},

        {"Controversies.Anticompetitive Practices", "controversy_anticompetitive"},
        {"Controversies.Privacy & Data Security", "controversy_privacy_data"},
        {"Controversies.Bribery & Fraud", "controversy_bribery_fraud"},
        {"Controversies.Governance Structures", "controversy_governance_structures"},
        {"Controversies.Customer Relations", "controversy_customer_relations"},
        {"Controversies.Product Safety & Quality", "controversy_product_safety"},
        {"Controversies.Human Rights Concerns", "controversy_human_rights"},
        {"Controversies.Energy & Climate Change", "controversy_energy_climate"},
        {"Controversies.Toxic Emissions & Waste", "controversy_toxic_emissions"},
        {"Controversies.Impact on Local Communities", "controversy_local_communities"},
        {"Controversies.Biodiversity & Land Use", "controversy_biodiversity"},
        {"Controversies.Other", "controversy_other"},
        {"Controversies.Marketing & Advertising", "controversy_marketing"},
        {"Controversies.Civil Liberties", "controversy_civil_liberties"},
        {"Controversies.Operational Waste (Non-Hazardous)", "controversy_operational_waste"},
        {"Controversies.Supply Chain Management", "controversy_supply_chain"},
        {"Controversies.Water Stress", "controversy_water_stress"},
        {"Controversies.Child Labor", "controversy_child_labor"},
        {"Controversies.Controversial Investments", "controversy_controversial_investments"}
    }
)
in
    #"Rename Columns"